//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ProdyC.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProdyCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ProdyCBaseListener : IProdyCListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>progLine</c>
	/// labeled alternative in <see cref="ProdyCParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgLine([NotNull] ProdyCParser.ProgLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>progLine</c>
	/// labeled alternative in <see cref="ProdyCParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgLine([NotNull] ProdyCParser.ProgLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProdyCParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctions([NotNull] ProdyCParser.FunctionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProdyCParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctions([NotNull] ProdyCParser.FunctionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProdyCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] ProdyCParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProdyCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] ProdyCParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnBlockLine([NotNull] ProdyCParser.FnBlockLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBlockLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnBlockLine([NotNull] ProdyCParser.FnBlockLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnBodyLine([NotNull] ProdyCParser.FnBodyLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnBodyLine([NotNull] ProdyCParser.FnBodyLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnBodyLineMore([NotNull] ProdyCParser.FnBodyLineMoreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnBodyLineMore</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnBodyLineMore([NotNull] ProdyCParser.FnBodyLineMoreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnReturnExprLine([NotNull] ProdyCParser.FnReturnExprLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnExprLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnReturnExprLine([NotNull] ProdyCParser.FnReturnExprLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnReturnLine([NotNull] ProdyCParser.FnReturnLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fnReturnLine</c>
	/// labeled alternative in <see cref="ProdyCParser.fnBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnReturnLine([NotNull] ProdyCParser.FnReturnLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProdyCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] ProdyCParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProdyCParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] ProdyCParser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineStmt</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineStmt([NotNull] ProdyCParser.LineStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineStmt</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineStmt([NotNull] ProdyCParser.LineStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineIf</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineIf([NotNull] ProdyCParser.LineIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineIf</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineIf([NotNull] ProdyCParser.LineIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineWhile</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineWhile([NotNull] ProdyCParser.LineWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineWhile</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineWhile([NotNull] ProdyCParser.LineWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineFor</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineFor([NotNull] ProdyCParser.LineForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineFor</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineFor([NotNull] ProdyCParser.LineForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineEOL</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineEOL([NotNull] ProdyCParser.LineEOLContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineEOL</c>
	/// labeled alternative in <see cref="ProdyCParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineEOL([NotNull] ProdyCParser.LineEOLContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>funcInvocLine</c>
	/// labeled alternative in <see cref="ProdyCParser.funcInvoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncInvocLine([NotNull] ProdyCParser.FuncInvocLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcInvocLine</c>
	/// labeled alternative in <see cref="ProdyCParser.funcInvoc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncInvocLine([NotNull] ProdyCParser.FuncInvocLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtAtrib</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtAtrib([NotNull] ProdyCParser.StmtAtribContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtAtrib</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtAtrib([NotNull] ProdyCParser.StmtAtribContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtInput</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtInput([NotNull] ProdyCParser.StmtInputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtInput</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtInput([NotNull] ProdyCParser.StmtInputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>stmtOutput</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtOutput([NotNull] ProdyCParser.StmtOutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stmtOutput</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtOutput([NotNull] ProdyCParser.StmtOutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lineFuncInvoc</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineFuncInvoc([NotNull] ProdyCParser.LineFuncInvocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lineFuncInvoc</c>
	/// labeled alternative in <see cref="ProdyCParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineFuncInvoc([NotNull] ProdyCParser.LineFuncInvocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>inputRead</c>
	/// labeled alternative in <see cref="ProdyCParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputRead([NotNull] ProdyCParser.InputReadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>inputRead</c>
	/// labeled alternative in <see cref="ProdyCParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputRead([NotNull] ProdyCParser.InputReadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputWriteVar</c>
	/// labeled alternative in <see cref="ProdyCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputWriteVar([NotNull] ProdyCParser.OutputWriteVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputWriteVar</c>
	/// labeled alternative in <see cref="ProdyCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputWriteVar([NotNull] ProdyCParser.OutputWriteVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputWriteStr</c>
	/// labeled alternative in <see cref="ProdyCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputWriteStr([NotNull] ProdyCParser.OutputWriteStrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputWriteStr</c>
	/// labeled alternative in <see cref="ProdyCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputWriteStr([NotNull] ProdyCParser.OutputWriteStrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>outputWriteExpr</c>
	/// labeled alternative in <see cref="ProdyCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputWriteExpr([NotNull] ProdyCParser.OutputWriteExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>outputWriteExpr</c>
	/// labeled alternative in <see cref="ProdyCParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputWriteExpr([NotNull] ProdyCParser.OutputWriteExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tipoInt</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipoInt([NotNull] ProdyCParser.TipoIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tipoInt</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipoInt([NotNull] ProdyCParser.TipoIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tipoString</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipoString([NotNull] ProdyCParser.TipoStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tipoString</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipoString([NotNull] ProdyCParser.TipoStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tipoFloat</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipoFloat([NotNull] ProdyCParser.TipoFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tipoFloat</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipoFloat([NotNull] ProdyCParser.TipoFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tipoBool</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTipoBool([NotNull] ProdyCParser.TipoBoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tipoBool</c>
	/// labeled alternative in <see cref="ProdyCParser.tipo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTipoBool([NotNull] ProdyCParser.TipoBoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ifstIf</c>
	/// labeled alternative in <see cref="ProdyCParser.ifst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstIf([NotNull] ProdyCParser.IfstIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifstIf</c>
	/// labeled alternative in <see cref="ProdyCParser.ifst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstIf([NotNull] ProdyCParser.IfstIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ifstIfElse</c>
	/// labeled alternative in <see cref="ProdyCParser.ifst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstIfElse([NotNull] ProdyCParser.IfstIfElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifstIfElse</c>
	/// labeled alternative in <see cref="ProdyCParser.ifst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstIfElse([NotNull] ProdyCParser.IfstIfElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>whilestWhile</c>
	/// labeled alternative in <see cref="ProdyCParser.whilest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhilestWhile([NotNull] ProdyCParser.WhilestWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>whilestWhile</c>
	/// labeled alternative in <see cref="ProdyCParser.whilest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhilestWhile([NotNull] ProdyCParser.WhilestWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>whilestDoWhile</c>
	/// labeled alternative in <see cref="ProdyCParser.whilest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhilestDoWhile([NotNull] ProdyCParser.WhilestDoWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>whilestDoWhile</c>
	/// labeled alternative in <see cref="ProdyCParser.whilest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhilestDoWhile([NotNull] ProdyCParser.WhilestDoWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>forstFor</c>
	/// labeled alternative in <see cref="ProdyCParser.forst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstFor([NotNull] ProdyCParser.ForstForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>forstFor</c>
	/// labeled alternative in <see cref="ProdyCParser.forst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstFor([NotNull] ProdyCParser.ForstForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="ProdyCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockLine([NotNull] ProdyCParser.BlockLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>blockLine</c>
	/// labeled alternative in <see cref="ProdyCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockLine([NotNull] ProdyCParser.BlockLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>condRelop</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondRelop([NotNull] ProdyCParser.CondRelopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>condRelop</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondRelop([NotNull] ProdyCParser.CondRelopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>condExpr</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondExpr([NotNull] ProdyCParser.CondExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>condExpr</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondExpr([NotNull] ProdyCParser.CondExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>condAnd</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondAnd([NotNull] ProdyCParser.CondAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>condAnd</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondAnd([NotNull] ProdyCParser.CondAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>condOr</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondOr([NotNull] ProdyCParser.CondOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>condOr</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondOr([NotNull] ProdyCParser.CondOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>condNot</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondNot([NotNull] ProdyCParser.CondNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>condNot</c>
	/// labeled alternative in <see cref="ProdyCParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondNot([NotNull] ProdyCParser.CondNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>atribVar</c>
	/// labeled alternative in <see cref="ProdyCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtribVar([NotNull] ProdyCParser.AtribVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>atribVar</c>
	/// labeled alternative in <see cref="ProdyCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtribVar([NotNull] ProdyCParser.AtribVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>atribVarStr</c>
	/// labeled alternative in <see cref="ProdyCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtribVarStr([NotNull] ProdyCParser.AtribVarStrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>atribVarStr</c>
	/// labeled alternative in <see cref="ProdyCParser.atrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtribVarStr([NotNull] ProdyCParser.AtribVarStrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="ProdyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprPlus([NotNull] ProdyCParser.ExprPlusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exprPlus</c>
	/// labeled alternative in <see cref="ProdyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprPlus([NotNull] ProdyCParser.ExprPlusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="ProdyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprMinus([NotNull] ProdyCParser.ExprMinusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exprMinus</c>
	/// labeled alternative in <see cref="ProdyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprMinus([NotNull] ProdyCParser.ExprMinusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="ProdyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprTerm([NotNull] ProdyCParser.ExprTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exprTerm</c>
	/// labeled alternative in <see cref="ProdyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprTerm([NotNull] ProdyCParser.ExprTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="ProdyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermMult([NotNull] ProdyCParser.TermMultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>termMult</c>
	/// labeled alternative in <see cref="ProdyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermMult([NotNull] ProdyCParser.TermMultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="ProdyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermDiv([NotNull] ProdyCParser.TermDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>termDiv</c>
	/// labeled alternative in <see cref="ProdyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermDiv([NotNull] ProdyCParser.TermDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="ProdyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermFactor([NotNull] ProdyCParser.TermFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>termFactor</c>
	/// labeled alternative in <see cref="ProdyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermFactor([NotNull] ProdyCParser.TermFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="ProdyCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorExpr([NotNull] ProdyCParser.FactorExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorExpr</c>
	/// labeled alternative in <see cref="ProdyCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorExpr([NotNull] ProdyCParser.FactorExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="ProdyCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorVar([NotNull] ProdyCParser.FactorVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorVar</c>
	/// labeled alternative in <see cref="ProdyCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorVar([NotNull] ProdyCParser.FactorVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="ProdyCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorNum([NotNull] ProdyCParser.FactorNumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factorNum</c>
	/// labeled alternative in <see cref="ProdyCParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorNum([NotNull] ProdyCParser.FactorNumContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
